"""Constants for the RWS Webcam Selfie integration."""
from __future__ import annotations

DOMAIN = "rws_webcam_selfie"

CONF_DEVICE_TRACKER = "device_tracker"
CONF_RADIUS = "radius"
CONF_MAX_DURATION = "max_duration"
CONF_ENABLED_CAMERAS = "enabled_cameras"
CONF_MEDIA_SUBDIR = "media_subdir"
CONF_FFMPEG_PATH = "ffmpeg_path"

DEFAULT_RADIUS = 2000  # metres
DEFAULT_MAX_DURATION = 180  # seconds, safety cap
DEFAULT_MEDIA_SUBDIR = "rws_webcam_selfie"
DEFAULT_FFMPEG_PATH = "ffmpeg"

EVENT_RECORDING_STARTED = f"{DOMAIN}_recording_started"
EVENT_RECORDING_COMPLETE = f"{DOMAIN}_recording_complete"
EVENT_RECORDING_FAILED = f"{DOMAIN}_recording_failed"

ATTR_CAMERA_ID = "camera_id"
ATTR_DURATION = "duration"

SERVICE_START_RECORDING = "start_recording"
SERVICE_STOP_RECORDING = "stop_recording"

# Baked snapshot of cameras from https://api.rwsverkeersinfo.nl/api/cameras/
# Regenerate with: python scripts/refresh_cameras.py
CAMERAS: list[dict] = [
    {
        "id": 4,
        "latitude": 52.185241,
        "longitude": 5.41449,
        "road": "A1",
        "near": "Amersfoort",
        "description": "Langs de A1, net ten westen van knooppunt Hoevelaken.",
        "embed_url": "https://stream.inmoves.nl/62/embed",
        "static_url": "https://stream.inmoves.nl/62",
        "hls_app": "rtplive",
        "hls_streamname": "IB_55.stream",
    },
    {
        "id": 13,
        "latitude": 52.332111,
        "longitude": 5.00709,
        "road": "A1",
        "near": "knooppunt Diemen",
        "description": "Langs de A1 ter hoogte van knooppunt Diemen.",
        "embed_url": "https://stream.inmoves.nl/185/embed",
        "static_url": "https://stream.inmoves.nl/185",
        "hls_app": "rtplive",
        "hls_streamname": "IB_1.stream",
    },
    {
        "id": 5,
        "latitude": 51.984371,
        "longitude": 5.089006,
        "road": "A2",
        "near": "Vianen",
        "description": "Langs de A2 ter hoogte van Vianen.",
        "embed_url": "https://stream.inmoves.nl/27/embed",
        "static_url": "https://stream.inmoves.nl/27",
        "hls_app": "rtplive",
        "hls_streamname": "IB_69.stream",
    },
    {
        "id": 6,
        "latitude": 51.802024,
        "longitude": 5.258304,
        "road": "A2",
        "near": "Zaltbommel",
        "description": "Langs de A2 ter hoogte van Zaltbommel.",
        "embed_url": "https://stream.inmoves.nl/6/embed",
        "static_url": "https://stream.inmoves.nl/6",
        "hls_app": "rtplive",
        "hls_streamname": "IB_26.stream",
    },
    {
        "id": 7,
        "latitude": 52.338749,
        "longitude": 4.816901,
        "road": "A4",
        "near": "Amsterdam-Sloten",
        "description": "Langs de A4 ter hoogte van Amsterdam-Sloten.",
        "embed_url": "https://stream.inmoves.nl/18/embed",
        "static_url": "https://stream.inmoves.nl/18",
        "hls_app": "rtplive",
        "hls_streamname": "IB_94.stream",
    },
    {
        "id": 8,
        "latitude": 52.292361,
        "longitude": 4.733519,
        "road": "A4",
        "near": "knooppunt De Hoek",
        "description": "Langs de A4 ter hoogte van knooppunt De Hoek.",
        "embed_url": "https://stream.inmoves.nl/19/embed",
        "static_url": "https://stream.inmoves.nl/19",
        "hls_app": "rtplive",
        "hls_streamname": "IB_99.stream",
    },
    {
        "id": 10,
        "latitude": 52.141402,
        "longitude": 4.510185,
        "road": "A4",
        "near": "Leiden",
        "description": "Langs de A4 tussen de verdiepte ligging en de aansluiting op de N11.",
        "embed_url": "https://stream.inmoves.nl/108/embed",
        "static_url": "https://stream.inmoves.nl/108",
        "hls_app": "rtplive",
        "hls_streamname": "IB_28.stream",
    },
    {
        "id": 9,
        "latitude": 52.198502,
        "longitude": 4.613871,
        "road": "A4",
        "near": "Roelofarendsveen",
        "description": "Langs de A4 ter hoogte van Roelofarendsveen.",
        "embed_url": "https://stream.inmoves.nl/12/embed",
        "static_url": "https://stream.inmoves.nl/12",
        "hls_app": "rtplive",
        "hls_streamname": "IB_64.stream",
    },
    {
        "id": 11,
        "latitude": 51.905703,
        "longitude": 4.369991,
        "road": "A4",
        "near": "Vlaardingen",
        "description": "Langs de A4 aan de noordzijde van de Beneluxtunnel.",
        "embed_url": "https://stream.inmoves.nl/39/embed",
        "static_url": "https://stream.inmoves.nl/39",
        "hls_app": "rtplive",
        "hls_streamname": "IB_70.stream",
    },
    {
        "id": 12,
        "latitude": 52.353151,
        "longitude": 5.247361,
        "road": "A6",
        "near": "Almere-Stad",
        "description": "Langs de A6, net ten zuiden van de aansluiting N305.",
        "embed_url": "https://stream.inmoves.nl/118/embed",
        "static_url": "https://stream.inmoves.nl/118",
        "hls_app": "rtplive",
        "hls_streamname": "IB_37.stream",
    },
    {
        "id": 15,
        "latitude": 52.304423,
        "longitude": 4.846994,
        "road": "A9",
        "near": "Amstelveen",
        "description": "Langs de A9 ter hoogte van Amstelveen.",
        "embed_url": "https://stream.inmoves.nl/34/embed",
        "static_url": "https://stream.inmoves.nl/34",
        "hls_app": "rtplive",
        "hls_streamname": "IB_207.stream",
    },
    {
        "id": 14,
        "latitude": 52.298045,
        "longitude": 4.94334,
        "road": "A9",
        "near": "knooppunt Holendrecht",
        "description": "Langs de A9 tussen knooppunt Holendrecht en de S111.",
        "embed_url": "https://stream.inmoves.nl/36/embed",
        "static_url": "https://stream.inmoves.nl/36",
        "hls_app": "rtplive",
        "hls_streamname": "IB_14.stream",
    },
    {
        "id": 16,
        "latitude": 52.383693,
        "longitude": 4.707818,
        "road": "A9",
        "near": "Rottepolderplein",
        "description": "Langs de A9 ter hoogte van knooppunt Rottepolderplein.",
        "embed_url": "https://stream.inmoves.nl/87/embed",
        "static_url": "https://stream.inmoves.nl/87",
        "hls_app": "rtplive",
        "hls_streamname": "IB_45.stream",
    },
    {
        "id": 19,
        "latitude": 52.328269,
        "longitude": 4.915606,
        "road": "A10",
        "near": "Amstel",
        "description": "Langs de A10 ter hoogte van knooppunt Amstel.",
        "embed_url": "https://stream.inmoves.nl/5/embed",
        "static_url": "https://stream.inmoves.nl/5",
        "hls_app": "rtplive",
        "hls_streamname": "IB_100.stream",
    },
    {
        "id": 17,
        "latitude": 52.422622,
        "longitude": 4.877047,
        "road": "A10",
        "near": "Coenplein Noord",
        "description": "Langs de A10 (binnenring).",
        "embed_url": "https://stream.inmoves.nl/3/embed",
        "static_url": "https://stream.inmoves.nl/3",
        "hls_app": "rtplive",
        "hls_streamname": "IB_19.stream",
    },
    {
        "id": 18,
        "latitude": 52.394732,
        "longitude": 4.843613,
        "road": "A10",
        "near": "knooppunt Westpoort",
        "description": "Langs de A10/A5 bij knooppunt Westpoort.",
        "embed_url": "https://stream.inmoves.nl/41/embed",
        "static_url": "https://stream.inmoves.nl/41",
        "hls_app": "rtplive",
        "hls_streamname": "IB_16.stream",
    },
    {
        "id": 20,
        "latitude": 52.355648,
        "longitude": 4.965291,
        "road": "A10",
        "near": "Watergraafsmeer",
        "description": "Langs de A10 tussen Zeeburgerbrug en knooppunt Watergraafsmeer.",
        "embed_url": "https://stream.inmoves.nl/61/embed",
        "static_url": "https://stream.inmoves.nl/61",
        "hls_app": "rtplive",
        "hls_streamname": "IB_33.stream",
    },
    {
        "id": 23,
        "latitude": 52.02471,
        "longitude": 4.665146,
        "road": "A12",
        "near": "knooppunt Gouwe",
        "description": "A12 ter hoogte van knooppunt Gouwe.",
        "embed_url": "https://stream.inmoves.nl/11/embed",
        "static_url": "https://stream.inmoves.nl/11",
        "hls_app": "rtplive",
        "hls_streamname": "IB_13.stream",
    },
    {
        "id": 22,
        "latitude": 52.055581,
        "longitude": 5.121922,
        "road": "A12",
        "near": "knooppunt Lunetten",
        "description": "Langs de N408 Laagravenseweg.",
        "embed_url": "https://stream.inmoves.nl/107/embed",
        "static_url": "https://stream.inmoves.nl/107",
        "hls_app": "rtplive",
        "hls_streamname": "IB_91.stream",
    },
    {
        "id": 21,
        "latitude": 52.059762,
        "longitude": 5.103187,
        "road": "A12",
        "near": "Oudenrijn",
        "description": "Langs de A12 ter hoogte van Kanaleneiland.",
        "embed_url": "https://stream.inmoves.nl/46/embed",
        "static_url": "https://stream.inmoves.nl/46",
        "hls_app": "rtplive",
        "hls_streamname": "IB_201.stream",
    },
    {
        "id": 24,
        "latitude": 52.005605,
        "longitude": 4.384789,
        "road": "A13",
        "near": "Delft",
        "description": "Langs de A13 tussen Delft en Delft-Zuid.",
        "embed_url": "https://stream.inmoves.nl/40/embed",
        "static_url": "https://stream.inmoves.nl/40",
        "hls_app": "rtplive",
        "hls_streamname": "IB_20.stream",
    },
    {
        "id": 25,
        "latitude": 51.909458,
        "longitude": 4.539384,
        "road": "A16",
        "near": "de Van Brienenoordbrug",
        "description": "Langs de A16 ter hoogte van Rotterdam Centrum.",
        "embed_url": "https://stream.inmoves.nl/45/embed",
        "static_url": "https://stream.inmoves.nl/45",
        "hls_app": "rtplive",
        "hls_streamname": "IB_205.stream",
    },
    {
        "id": 27,
        "latitude": 51.77666,
        "longitude": 4.650273,
        "road": "A16",
        "near": "Dordrecht",
        "description": "Langs de A16 bij de aansluiting N3 en N217.",
        "embed_url": "https://stream.inmoves.nl/121/embed",
        "static_url": "https://stream.inmoves.nl/121",
        "hls_app": "rtplive",
        "hls_streamname": "IB_50.stream",
    },
    {
        "id": 26,
        "latitude": 51.830175,
        "longitude": 4.622009,
        "road": "A16",
        "near": "Zwijndrecht",
        "description": "Langs de A16 ter hoogte van Zwijndrecht.",
        "embed_url": "https://stream.inmoves.nl/13/embed",
        "static_url": "https://stream.inmoves.nl/13",
        "hls_app": "rtplive",
        "hls_streamname": "IB_41.stream",
    },
    {
        "id": 28,
        "latitude": 51.924202,
        "longitude": 4.360839,
        "road": "A20",
        "near": "Knooppunt Kethelplein",
        "description": "Langs de A20 ter hoogte van knooppunt Kethelplein (A4)",
        "embed_url": "https://stream.inmoves.nl/198/embed",
        "static_url": "https://stream.inmoves.nl/198",
        "hls_app": "rtplive",
        "hls_streamname": "IB_32.stream",
    },
    {
        "id": 29,
        "latitude": 51.83546,
        "longitude": 4.945882,
        "road": "A27",
        "near": "Gorinchem",
        "description": "Langs de A27 ter hoogte van de Merwedebrug bij Gorinchem.",
        "embed_url": "https://stream.inmoves.nl/15/embed",
        "static_url": "https://stream.inmoves.nl/15",
        "hls_app": "rtplive",
        "hls_streamname": "IB_22a.stream",
    },
]


def hls_url(camera: dict) -> str:
    """Build the HLS playlist URL for a camera."""
    return (
        f"https://stream.inmoves.nl/{camera['hls_app']}/"
        f"{camera['hls_streamname']}/playlist.m3u8"
    )
